version: '2'
plugins:
  rubocop:
    enabled: true
  reek:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        ruby:
          mass_threshold: 18
  markdownlint:
    enabled: true
exclude_patterns:
- spec/**/*
- "**/vendor/**/*"
