language: ruby
rvm:
- 2.5.0
notifications:
  slack: biavati:80UJ1W4zUYesbsap2cNqZBLV
env:
- RAILS_ENV=test
before_install:
- gem update --system
script:
- bin/rake db:create db:migrate
- bin/rake spec
