language: ruby
rvm:
- 2.5.0
notifications:
  slack: biavati:80UJ1W4zUYesbsap2cNqZBLV
before_install:
- gem update --system
script:
- bin/rake db:create db:migrate RAILS_ENV=test
- bin/rake spec RAILS_ENV=test
